export const PROJECTS = [
    {
        name: "QUIZ APPLICATION",
        code:
            "https://github.com/Madhan-SWE/ZEN-class-tasks/tree/master/Day17-120920/QuizApp",
        demo: "https://zen-fermat-35f995.netlify.app",
        description:
            "Quiz game front end application developed with OPEN Trivia DB APIs",
        languages: [
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
        ],
        categories: ["All"],
    },
    {
        name: "QUIZ APPLICATION",
        code:
            "https://github.com/Madhan-SWE/ZEN-class-tasks/tree/master/Day17-120920/QuizApp",
        demo: "https://zen-fermat-35f995.netlify.app",
        description:
            "Quiz game front end application developed with OPEN Trivia DB APIs",
        languages: [
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
        ],
        categories: ["All"],
    },
    {
        name: "QUIZ APPLICATION",
        code:
            "https://github.com/Madhan-SWE/ZEN-class-tasks/tree/master/Day17-120920/QuizApp",
        demo: "https://zen-fermat-35f995.netlify.app",
        description:
            "Quiz game front end application developed with OPEN Trivia DB APIs",
        languages: [
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
        ],
        categories: ["All"],
    },
    {
        name: "QUIZ APPLICATION",
        code:
            "https://github.com/Madhan-SWE/ZEN-class-tasks/tree/master/Day17-120920/QuizApp",
        demo: "https://zen-fermat-35f995.netlify.app",
        description:
            "Quiz game front end application developed with OPEN Trivia DB APIs",
        languages: [
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
        ],
        categories: ["All"],
    },
    {
        name: "QUIZ APPLICATION",
        code:
            "https://github.com/Madhan-SWE/ZEN-class-tasks/tree/master/Day17-120920/QuizApp",
        demo: "https://zen-fermat-35f995.netlify.app",
        description:
            "Quiz game front end application developed with OPEN Trivia DB APIs",
        languages: [
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
            "html",
            "css",
            "typescript",
        ],
        categories: ["All"],
    },
];
